# Generated by Django 6.0.3 on 2026-04-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='session_key',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('session_key', 'menu_item'), name='unique_session_menu_item'),
        ),
    ]
