# Generated by Django 5.2.12 on 2026-04-05 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cartitem_id_alter_category_id_and_more'),
        ('main', '0002_cartitem_session_key_and_more'),
    ]

    operations = [
    ]
